[build]
# Default target, can still be overridden explicitly with the `--target` flag.
target = "x86_64-asos.json"

[toolchain]
channel = "nightly"
components = ["rust-src"]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = [
    # Provides implementations for stuff like memset, etc
    "compiler-builtins-mem"
]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"

[term]
verbose = true

[dependencies]
